config/routes.rb
Railslist::Application.routes.draw do
  root :to => 'items#index'
  resources :items, :only => [:index, :new, :create, :show, :edit, :update, :destroy]

end

app/models/item.rb
class Item < ActiveRecord::Base
	attr_accessible :title, :description, :price, :item_key

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	require 'SecureRandom'

	def index
		@item = Item.new
		@items = Item.all
	end

	def create
		@item = Item.create(params[:item])
		item_key = SecureRandom.urlsafe_base64
		@item[:item_key] = item_key

		redirect_to item_path(@item.id) if @item.save
	end

	def show
		@item = Item.find(params[:id])
	end

	def edit
		@item = Item.find(params[:id])
	end

	def update
		Item.update(params[:id], params[:item])
		@item = Item.find(params[:id])
	end

	def destroy
		@item = Item.find(params[:id])
		@item.destroy
		redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/edit.html.erb
<h1>Editing your item</h1>

Title: <%= @item.title %><br />
Description: <%= @item.description %><br />
Price: <%= @item.price %><br />

<%= form_for @item, html: {class: "nifty_form"} do |f| %>
  <%= f.text_field :title, placeholder: 'title' %><br />
  <%= f.text_area :description, size: "60x12", placeholder: 'description' %><br />
  <%= f.text_field :price, placeholder: 'price' %><br />
  <%= f.submit "Edit Item" %>
<% end %>

app/views/items/index.html.erb
Welcome to ShireList

<h1>What would you like to post?</h1>
<%= form_for @item, html: {class: "nifty_form"} do |f| %>
  <%= f.text_field :title, placeholder: 'title' %><br />
  <%= f.text_area :description, size: "60x12", placeholder: 'description' %><br />
  <%= f.text_field :price, placeholder: 'price' %><br />
  <%= f.submit "add item" %>
<% end %>
<br />
<ul>
	<% @items.each do |item| %>
		<li><%= item.title %>: <%= item.description %> (<%= item.price %>)</li>
	<% end %>
</ul>	

app/views/items/show.html.erb
<h1>You have posted the following to ShireList</h1>

Title: <%= @item.title %><br />
Description: <%= @item.description %><br />
Price: <%= @item.price %><br />

<%= link_to "Edit this item", edit_item_path %>
<%= link_to "Delete this item", @item, :method => :delete %>

app/views/items/update.html.erb
<br />Congratulations you've updated to:<br /> 
Title: <%= @item.title %><br />
Description: <%= @item.description %><br />
Price: <%= @item.price %><br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shirelist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<a href = "/">Home</a><br>
<%= yield %>

</body>
</html>